### ISSUE TITLE
error: package directory 'duallog' does not exist, after install

### ISSUE THREAD

**Issue by meetmagdalene** [acschaefer/duallog#1]
Hi there,

Very interested in using this module but I got an error on install.

Here is my output:
ran in my console `$ sudo python setup.py install`
```
running install
running bdist_egg
running egg_info
writing duallog.egg-info/PKG-INFO
writing top-level names to duallog.egg-info/top_level.txt
writing dependency_links to duallog.egg-info/dependency_links.txt
error: package directory 'duallog' does not exist
```

I'm on Linux Ubuntu 16.08.
Python 2.7.12

Tried running via python3 just to see what would happen but it failed instead for an ImportError:
```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import setuptools
ImportError: No module named 'setuptools'
```

Any help would be greatly appreciated!

**Comment by acschaefer** [comment]
Thank you for testing duallog! I could replicate your problem and I am currently working on a solution, which I will publish in the next hours.

**Comment by acschaefer** [comment]
It turned out that the folder structure of the package was messed up: All code has to go into a folder that is named after the package (in this case `duallog/duallog`). So I restored the folder structure and tested the installation. For me, it works fine now. I hope it does for you, too!

**Comment by meetmagdalene** [comment]
That took care of it for me, thank you!

**Comment by acschaefer** [comment]
Thanks for pointing out this issue!
