### ISSUE TITLE
Module 'duallog' has no attribute 'setup'

### ISSUE THREAD

**Issue by phcamargo23** [acschaefer/duallog#2]
Hi,

**Installation:**
λ python setup.py install                                                               
running install                                                                         
running bdist_egg                                                                       
running egg_info                                                                        
creating duallog.egg-info                                                               
writing duallog.egg-info\PKG-INFO                                                       
writing dependency_links to duallog.egg-info\dependency_links.txt                       
writing top-level names to duallog.egg-info\top_level.txt                               
writing manifest file 'duallog.egg-info\SOURCES.txt'                                    
reading manifest file 'duallog.egg-info\SOURCES.txt'                                    
writing manifest file 'duallog.egg-info\SOURCES.txt'                                    
installing library code to build\bdist.win-amd64\egg                                    
running install_lib                                                                     
running build_py                                                                        
creating build                                                                          
creating build\lib                                                                      
creating build\lib\duallog                                                              
copying duallog\duallog.py -> build\lib\duallog                                         
copying duallog\__init__.py -> build\lib\duallog                                        
creating build\bdist.win-amd64                                                          
creating build\bdist.win-amd64\egg                                                      
creating build\bdist.win-amd64\egg\duallog                                              
copying build\lib\duallog\duallog.py -> build\bdist.win-amd64\egg\duallog               
copying build\lib\duallog\__init__.py -> build\bdist.win-amd64\egg\duallog              
byte-compiling build\bdist.win-amd64\egg\duallog\duallog.py to duallog.cpython-37.pyc   
byte-compiling build\bdist.win-amd64\egg\duallog\__init__.py to __init__.cpython-37.pyc 
creating build\bdist.win-amd64\egg\EGG-INFO                                             
copying duallog.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO                 
copying duallog.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO              
copying duallog.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO     
copying duallog.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO            
zip_safe flag not set; analyzing archive contents...                                    
creating dist                                                                           
creating 'dist\duallog-0.2-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it      
removing 'build\bdist.win-amd64\egg' (and everything under it)                          
Processing duallog-0.2-py3.7.egg                                                        
Removing c:\users\phcam\anaconda3\lib\site-packages\duallog-0.2-py3.7.egg               
Copying duallog-0.2-py3.7.egg to c:\users\phcam\anaconda3\lib\site-packages             
duallog 0.2 is already the active version in easy-install.pth                           
                                                                                        
Installed c:\users\phcam\anaconda3\lib\site-packages\duallog-0.2-py3.7.egg              
Processing dependencies for duallog==0.2                                                
Finished processing dependencies for duallog==0.2

**Ipython test:** module 'duallog' has no attribute 'setup'

**Config**: Windows 10, Python 3.7.0, IPython 6.5.0

**Comment by acschaefer** [comment]
Thank you for your feedback! I will try to reproduce this error within the next 24 hours.

**Comment by acschaefer** [comment]
I found the problem: I was missing the `import` command in the `__init__.py` file. It makes sure all modules are imported when you import the package. The solution is committed as 053e3e77cf103bafcc299f9bdbff1973bc23883f.

Could you please pull the update and check if `duallog` now works for you?

Thank you again for your feedback!

**Comment by michalzimniak** [comment]
Still the same issue:


```
# python3 setup.py install
running install
running bdist_egg
running egg_info
creating duallog.egg-info
writing duallog.egg-info/PKG-INFO
writing dependency_links to duallog.egg-info/dependency_links.txt
writing top-level names to duallog.egg-info/top_level.txt
writing manifest file 'duallog.egg-info/SOURCES.txt'
reading manifest file 'duallog.egg-info/SOURCES.txt'
writing manifest file 'duallog.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/duallog
copying duallog/duallog.py -> build/lib/duallog
copying duallog/__init__.py -> build/lib/duallog
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/duallog
copying build/lib/duallog/duallog.py -> build/bdist.linux-x86_64/egg/duallog
copying build/lib/duallog/__init__.py -> build/bdist.linux-x86_64/egg/duallog
byte-compiling build/bdist.linux-x86_64/egg/duallog/duallog.py to duallog.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/duallog/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying duallog.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying duallog.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying duallog.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying duallog.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/duallog-0.3-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing duallog-0.3-py3.6.egg
Copying duallog-0.3-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding duallog 0.3 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/duallog-0.3-py3.6.egg
Processing dependencies for duallog==0.3
Finished processing dependencies for duallog==0.3
```

Test:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import duallog
>>> duallog.setup("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'duallog' has no attribute 'setup'
```

**Comment by acschaefer** [comment]
Thank you for your feedback! I could reproduce the error on Windows 10, Python 3.7.1. I was able to resolve the issue, too, by replacing `from duallog import *` by `from .duallog import *` in `__init__.py`. Does this work for you, too?

By the way, I will soon release the package on PyPI in order to simplify installation.

**Comment by acschaefer** [comment]
The package is now available on PyPI, too. So the following installation routine should also work:
```bash
pip install duallog
```

**Comment by acschaefer** [comment]
Does the installation now work for you? Feedback is highly appreciated! =)

**Comment by phcamargo23** [comment]
Works with pip. Thanks!

**Comment by phcamargo23** [comment]
Nice! Works with pip. Thanks!

**Comment by acschaefer** [comment]
Thank you for your feedback!
